version: "3.8"

services:
  purecycle-backend-laravel:
    container_name: purecycle-backend-laravel
    build: .
    restart: always
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - /home/ubuntu/purecycle/purecycle-backend-laravel:/var/www/html
    environment:
      - TZ=Asia/Manila