version: "3.8"

services:
  nginx-project:
    container_name: nginx-project
    image: nginx:alpine
    restart: always
    depends_on:
      - php-project
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/purecycle/purecycle-backend-laravel:/usr/share/nginx/html
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: Asia/Manila

  php-project:
    container_name: php-project
    build: ./php
    restart: always
    expose:
      - "9000"
    volumes:
      - /home/ubuntu/purecycle/purecycle-backend-laravel:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    environment:
      TZ: Asia/Manila