server {
    listen 80;
    listen 443 ssl;
    
    server_name phpmyadmin.pure-cycle.online;

    # SSL Configuration
    ssl_certificate     /etc/nginx/ssl/cloudflare.crt;
    ssl_certificate_key /etc/nginx/ssl/cloudflare.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    # Upload limits
    client_max_body_size 256M;

    location / {
        proxy_pass http://phpmyadmin:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
